### ISSUE TITLE
CSS and Javascript in Will's responses?

### ISSUE THREAD

**Issue by deeplook** [skoczen/will#218] opened 2016-03-18 15:23 UTC
I'm pretty new to Will, and like it very much! After playing a bit with it I saw that HipChat (and Will) allows HTML in responses, unlike Slack. So I played a bit and could output something simple as `<p>foo <strong>bar</strong></p>`, but only in group rooms (in 1-1 rooms this seems to be not working and a bug). But when I add `<html> and <body>`, though these are output too. So I wonder if it's possible to include custom CSS and possible Javascript in HTML content output with: `self.reply(message, content, html=True)` and if these would be cashed somehow if so?

The purpose would be for example to include Bootstrap styling or output graphs rendered with plot.ly in Will's responses.

Maybe this is possible using web hooks, but I'm not there yet, and I haven't seen concise examples for using web hooks on http://skoczen.github.io/will/

**Comment by dennisobrien** [comment] 2016-04-07 19:07
I'm curious about this same thing.  It looks like hipchat supports a small subset of HTML.

https://www.hipchat.com/docs/api/method/rooms/message

> html - Message is rendered as HTML and receives no special treatment. Must be valid HTML and entities must be escaped (e.g.: &amp; instead of &). May contain basic tags: a, b, i, strong, em, br, img, pre, code, lists, tables.

**Comment by mbr-sn** [comment] 2016-05-30 14:26
When you check the HipChat API, you will see that only messages to rooms support HTML:
https://www.hipchat.com/docs/apiv2/method/send_room_notification

Direct 1-1 messages do not:
https://www.hipchat.com/docs/apiv2/method/send_message
(you can only send a string, but no formatting)

So it's not a bug, but a limitation of HipChat.
;-)

**Comment by AndrewBurdyug** [comment] 2016-05-30 23:05
> Direct 1-1 messages do not:

Actually, direct messages can be in html format: 

https://www.hipchat.com/docs/apiv2/method/private_message_user

>**string 	message_format** 	

>Determines how the message is treated by our server and rendered inside HipChat applications

>html - Message is rendered as HTML and receives no special treatment. Must be valid HTML and entities must be escaped (e.g.: '&amp;' instead of '&'). May contain basic tags: a, b, i, strong, em, br, img, pre, code, lists, tables.
text - Message is treated just like a message sent by a user. Can include @mentions, emoticons, pastes, and auto-detected URLs (Twitter, YouTube, images, etc).

>Valid values: html, text.

>Defaults to 'text'.

**Comment by mbr-sn** [comment] 2016-06-01 14:15
Hmm, it does not work for me.

So I checked mixins/hipchat.py

`send_direct_message` has a comment with
https://www.hipchat.com/docs/apiv2/method/private_message_user
however it uses 
`PRIVATE_MESSAGE_URL = "https://%(server)s/v2/user/%(user_id)s/message?auth_token=%(token)s"`

This corresponds to the api call
https://www.hipchat.com/docs/apiv2/method/send_message
as I had written above. This api call does not support HTML, which explains why it does not work I guess.

The question then is: 
Why is there a different URL in the comment in that method, if that is not the actual api call used?

**Comment by brandonsturgeon** [comment] 2017-02-07 22:59
@deeplook It looks like Hipchat has no plans to expand on their current HTML set, which likely means almost no css/styling support, and surely no Javascript support. 😞

**Comment by skoczen** [comment] 2017-05-07 22:56
Broadly on this, there's been a change to the hipchat API to now support HTML in 1-1 messages, which 0.9.4 added to will.  Beyond that, a bigger subset of HTML and css aren't supported by hipchat - but they well may be by future output mediums. 

I'm closing this issue up as we're doing the best we can for hipchat's support at the moment, but keeping the broader desire for the maximum subset of richness a platform supports in mind for future expansion!

If that doesn't hit your needs, please reopen, and let's keep talking!

**Closed by skoczen** 2017-05-07 22:56 UTC
