### ISSUE TITLE
Trouble getting Will to connect

### ISSUE THREAD

**Issue by redbluered** [skoczen/will#121] opened 2015-04-02 15:54 UTC
error: No socket could be created -- (('0.0.0.0', 443): [Errno 13] Permission denied)
DEBUG    Connecting to 54.83.41.103:5222
DEBUG    Event triggered: socket_error
ERROR    Could not connect to 54.83.41.103:5222. Socket Error #111: Connection refused
DEBUG    No remaining DNS records to try.
DEBUG    Waiting 2.05586041425 seconds before connecting.
DEBUG    DNS: Querying SRV records for chat.btf.hipchat.com
DEBUG    DNS: No SRV records for chat.btf.hipchat.com.
DEBUG    DNS: Querying chat.btf.hipchat.com for AAAA records.
DEBUG    DNS: No AAAA records for chat.btf.hipchat.com
DEBUG    DNS: Querying chat.btf.hipchat.com for A records.
DEBUG    Connecting to 54.83.41.103:5222
DEBUG    Event triggered: socket_error
ERROR    Could not connect to 54.83.41.103:5222. Socket Error #111: Connection refused
DEBUG    Waiting 1.89736263227 seconds before connecting.

Any ideas?

**Comment by skoczen** [comment] 2015-04-03 06:39
Hey @redbluered ,

Thanks for raising this.

Some clarification - are you seeing `HIPCHAT_SERVER` not come through as originally listed?  Do you have additional output?

Thanks!
-Steven

**Comment by redbluered** [comment] 2015-04-03 16:37
Hi! Thank you for helping.

I'm now seeing this error:

sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
InvalidJID: Domain contains illegal characters

and the bot isn't joining any rooms. It is connecting to our private hipchat server though. i can see it says authenticated correctly and gets a list of rooms, but it never joins the room.

**Comment by skoczen** [comment] 2015-04-03 16:39
Absolutely! 

Hrm.  Something seems wrong in your config.  Can you paste in the relevant sections of your config.py and environment?

**Comment by redbluered** [comment] 2015-04-03 16:49
I only have two lines added to the config file.

HIPCHAT_SERVER = "my.hipchatserver.com"
and
HTTPSERVER_PORT = "9000"

everything else is just the default settings. no default room, no public url, no v1_token are the only warnings. 

i'm not sure it's ignoring things with a # in front of them. i have some lines i added and then commented out that it either cached or is still reading.

e.g. I have two #ROOMS = ['room name fake'] lines in there that i commented out yet when i start it up, it says 
--
! Warning: no DEFAULT_ROOM found in the environment or config.  Defaulting to 'room name fake', the first one.
--
not sure how it's reading that room name fake setting at all unless it's cached.


ideas?

**Comment by skoczen** [comment] 2015-04-23 19:33
Hey @redbluered , 

Thanks for your patience.  Rooms (and all config) can also be passed in via environment variables.  

Are you still seeing this?  If so, starting with a clean env is a good place to start.

Lines that start with `#` are definitely being ignored, unless your python is broken - there's no fancy parsing happening there!

**Comment by skoczen** [comment] 2015-05-30 18:28
Closing this up, since it's been a month and a half - please reopen if you're still having trouble!

**Closed by skoczen** 2015-05-30 18:28 UTC

**Comment by acidjunk** [comment] 2015-08-03 10:40
I have the same problem. Configured stuff from env. Then the first run it was running smoothly. After that I get:

```
Bootstrapping complete.

Starting core processes:
CRITICAL Error bootstrapping xmpp:

Traceback (most recent call last):
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/will/main.py", line 373, in bootstrap_xmpp
    self.start_xmpp_client()
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/will/listener.py", line 16, in start_xmpp_client
    ClientXMPP.__init__(self, "%s/bot" % settings.USERNAME, settings.PASSWORD)
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/sleekxmpp/clientxmpp.py", line 65, in __init__
    BaseXMPP.__init__(self, jid, 'jabber:client')
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/sleekxmpp/basexmpp.py", line 70, in __init__
    self.requested_jid = JID(jid, cache_lock=True)
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/Users/acidjunk/.virtualenvs/willy/lib/python2.7/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
InvalidJID: Domain contains illegal characters
```

**Comment by acidjunk** [comment] 2015-08-03 10:41
FYI: I already tried starting with a new and clean env. Also restarted redis server a couple of times.

**Comment by acidjunk** [comment] 2015-08-03 10:43
Just to confirm: I think you only get this error when you use JABBER_USERNAME instead of JABBER_ID !

**Comment by oefterdal** [comment] 2016-02-03 09:19
@acidjunk I can confirm that it helped with using the JABBER_USERNAME. Thank you.

**Comment by acidjunk** [comment] 2016-02-03 09:54
awesome :)
