### ISSUE TITLE
Will doesn't like SIGTERM

### ISSUE THREAD

**Issue by sivy** [skoczen/will#132] opened 2015-05-04 16:22 UTC
From what I've seen, upon launch Will starts 3 new processes - one each for the scheduler, XMPP, and web server (bottle). Normally on `KeyboardInterupt` or `SystemExit`, Will stops each of these threads cleanly.

I've been experimenting with running Will under [envconsul](https://github.com/hashicorp/envconsul), which watches and loads configs from the Consul KV store and inserts them into the ENV before starting Will. The trouble seems to be that when changes occur to the Consul KV data, envconsul sends a `SIGTERM` to Will, which ends up killing the original process, but not the three spawned processes. envconsul then restarts Will, which spawns 3 new processes, leaving the original three running.

I did take a hack at a patch but I'm crap at threading code, and have not yet made it work. Expect it will have to do with registering a `SIGTERM` handler (correctly) then shutting things down when it's fired.

**Comment by skoczen** [comment] 2015-05-05 00:46
Hey Steve,




Yep, that sounds about right - if you can catch the SIGTERM and handle it, you may be able to handle this situation.




But - will also modifies the environment as a way of sharing state amongst the threads (not ideal, but I’m also not a thread-programming wizard).  If those changes cause Consul to restart the env, I’m a bit skeptical that the setup you have is going to jive with how he’s currently written.  However, if there’s anything I can do to help out on that, I’m definitely open to tossing what I know over the fence!




Otherwise, the place to look is going to be in the main.py file, where the KeyboardInterrupt is handled.  You should be able to catch somewhere around there!




If that doesn’t get you unblocked, ping on this - I won’t have spare cycles this week for sure, but next week is possible (though in honesty, I won’t say likely!)




-Steven

**Comment by sivy** [comment] 2015-05-05 01:13
I'll take a look at it. Envconsul only changes the environment; it does not back-port env changes to consul.

--
Steve - steveivy@gmail.com

**Comment by skoczen** [comment] 2015-09-11 16:34
Closing this, as I think it's a dupe of #181.  Please reopen if I have it wrong!

**Closed by skoczen** 2015-09-11 16:34 UTC
