### ISSUE TITLE
will 'Will' support Atlasssian's Stride?

### ISSUE THREAD

**Issue by chutes** [skoczen/will#294] opened 2017-10-24 17:43 UTC
Or does it already support it?

**Comment by skoczen** [comment] 2017-10-24 20:57
That's the goal, but Atlasssian isn't being terribly forthcoming on what Stride's API and capabilities will be.

In the big picture, that's a big part of why I've moved Will to abstracted backends for the 2.x release - either I or someone else can build a Stride backend, and we can all keep our plugins and work.

As far as Stride specifically, there *is* no spec, so it's impossible to say.

I've contacted their team directly and submitted a [support topic](https://community.atlassian.com/t5/Stride-questions/Stride-XMPP-and-API-support-and-timeline/qaq-p/657424).  

I've heard back in private email (but not the public topic), and here's what I know thus far (it's mostly marketing speak):


> There are no planned changes to the HipChat XMPP protocol. If you are seeing inconsistencies, they are probably not intentional. If you file a support request with details, we can try to help you track it down. Feel free to mention this ticket for context.
> 
> Unlike HipChat, Stride is not built using XMPP and will not support an XMPP interface. Instead, 
>If you'd like early access to that API, please sign up here and we'll get you in:     https://developer.atlassian.com/cloud/stride/
> 
> HipChat users will be moving to Stride group-by-group, on their own timetable. We've just become the process of inviting folks to migrate. Because the Stride API and apps are different (and more capable!) that HipChat integrations, customers will need to install and configure new applications in Stride after they migrate.
> 
> We totally agree that integrations to HipChat are hugely valuable. In building Stride, however, we realized that we needed to make some fundamental changes in order to provide the kind of capabilities and dev experience that we wanted. We understand that it will mean work for developers to support Stride, but we believe the long term enhancements will be worth it.
> 

I'll keep this issue updated as we know more - if anyone is game to take on owning the Stride backend, or has more information, please chime in!

**Comment by skoczen** [comment] 2017-11-19 23:25
For everyone who's following this, Atlasssian is saying that XMPP will *not* be supported, leaving Will and all other current integrations out in the cold.   They say that this is a technical decision, and thus far, have not been open to feedback from partners that XMPP is a crucial bit of the stack.

At this point, here's what I'd recommend if your company depends on a Will-Hipchat integration:

1. Please contact Atlasssian via the [contact the CEOs](https://www.atlassian.com/company/contact/contact-ceos) form, and tell them that your company relies on XMPP functionality, and that it's critical that Stride support it.

2. Upgrade to Will 2, and start investigating other options.  Slack is the obvious one, but Will also supports rocket.chat, and is very open to adding new backends.

3. If switching off HipChat isn't viable, sign up for the Stride beta, keep a close eye on the specs, and consistently provide feedback that you'll need a real-time, non-public endpoint way for bots to interact.  I've personally moved off of HipChat at my orgs, so I'm not going to be as sharp on this as someone with a vested interest.

**To be absolutely clear**: If Atlasssian provides a way for us to get Will (and bots, generally) to interact with Stride, we'll build it in to Will.  But we're completely at their mercy, and they will be killing off the HipChat XMPP functionality that Will relies on at some point.  If your org depends on it, I'd start making other plans.

If anyone gets more information, please add it to this issue - hoping this all gets resolved well, and soon!

**Comment by lingfish** [comment] 2018-02-24 05:38
(Crossposted from [errbot](https://github.com/errbotio/errbot/issues/937#issuecomment-368202135))

Ok, so this is the situation from Atlassian:

For Data Centre/Server:

* XMPP itself is not retired, but the supported way to use it is over BOSH
* The other option is using the v2 API, including webhooks (which implies some form of web server required at the bot end)

For Stride:

* No XMPP support at all, v2 API is the only way forward

So yeah, looking ahead, the API seems the right way to go, or using something like [punjab](https://github.com/twonds/punjab) as a proxy.

Atlassian themselves seem to have a [good, basic library](https://bitbucket.org/atlassianlabs/ac-flask-hipchat/src) based on Flask, perhaps as a reference?

**Comment by skoczen** [comment] 2018-03-21 20:22
Update:  Their API seems to be more stable, and they've reached out:
https://community.atlassian.com/t5/Stride-questions/Stride-XMPP-and-API-support-and-timeline/qaq-p/657424#M1654

**Comment by lingfish** [comment] 2018-03-28 21:50
So, @skoczen, do you know your plans here?

**Comment by lingfish** [comment] 2018-03-30 06:08
Yep, I understand re time.  I'm actually not interested (right now) in Stride, or it's support.  We've just rolled out HipChat, so that's what I'm keen on.

Atlassian may have bungled this a bit, but hey, Slack are [dropping IRC and XMPP too](https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP).

I'll get time for it eventually too, but perhaps my code example reference above may help someone else sooner.

**Comment by skoczen** [comment] 2018-04-02 21:35
Hey @lingfish , yeah, the issue is more that Atlassian is moving to an entirely new system, tossing away any integrations developers have built - and the migration is forced.  HipChat is going to be killed.

It's also important to note that XMPP is the only real-time interface for HipChat - instead of an extra option as it is in Slack et al.  

In most big migrations like this for an enterprise provider, you'd provide a legacy backwards-compatible adapter so that your clients didn't have to spend resources rebuilding their business components because you want to improve your platform.  Or, you provide a clear, long deprecation and support schedule.

Why HipChat didn't choose to do either of those is beyond me, but it certainly cost them our business.  As mentioned, I'm very much a +1 to stride support if you or anyone else has interest!

**Comment by lingfish** [comment] 2018-04-04 05:41
Yep, understood @skoczen. I guess it is worth pointing out that XMPP right now is still there (HipChat), it's just disabled.

> HipChat is going to be killed

All indications I see, if you mean the whole product, is that HipChat Server isn't going anywhere, only the cloud version.

**Comment by Ashex** [comment] 2018-07-27 10:22
Hipchat *and* Stride are going away in favor of Slack:

https://techcrunch.com/2018/07/26/atlassians-hipchat-and-stride-to-be-discontinued-with-slack-buying-up-the-ip/

**Comment by wontonst** [comment] 2019-01-29 22:56
Closing this issue since HipChat/Stride are being discontinued.

**Closed by wontonst** 2019-01-29 22:56 UTC
